services:
  ai-agent:
    build: .
    container_name: gemini-ai-agent
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - sqlite_data:/app
    restart: always
  

volumes:
  sqlite_data: